---
all:
  hosts:
    utils.dummy:
  children:
    control_plane:
      hosts:
        controller1.dummy:
        controller2.dummy:
        controller3.dummy:
    execution_nodes:
      hosts:
        exec1.dummy:
        exec2.dummy:
